#!/usr/bin/env python
import os
import sys

if len(sys.argv) == 2:
	filename = sys.argv[1]
	path = ""
	try:
		path = filename[:filename.rindex('/')] + '/'
	except:
		pass
	os.system('gcc -std=c99 -Wall -Werror -Wextra -I ~/development/c/libft/include \
        -L ~/development/c/libft -lft -o ' + filename.split('.')[0] + ' ' + filename)
else:
	print 'Usage: compile /path/to/exname.c'
        
